import jsPDF from "jspdf";
import { calculateTrustScore, categorize, sohPercent } from "./trust-score";

export interface BatteryRecord {
  id: string;
  battery_code: string;
  manufacturer: string;
  model: string | null;
  manufacturing_date: string;
  chemistry: string;
  original_capacity_kwh: number;
  current_capacity_kwh: number;
  charge_cycles: number;
  avg_operating_temp_c: number;
  fast_charging_freq_pct: number;
  voltage_v: number;
  current_a: number;
  fault_count: number;
  fault_records: string | null;
  maintenance_notes: string | null;
  inspection_notes: string | null;
  lifecycle_status: string;
  trust_score: number | null;
}

export function generatePdfReport(b: BatteryRecord) {
  const score = b.trust_score ?? calculateTrustScore(b);
  const cat = categorize(score);
  const soh = sohPercent(b);
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();

  // header
  doc.setFillColor(20, 32, 60);
  doc.rect(0, 0, W, 80, "F");
  doc.setTextColor(120, 200, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("VoltPass", 40, 45);
  doc.setFontSize(10);
  doc.setTextColor(200, 220, 255);
  doc.text("Battery Passport & Trust Score Report", 40, 62);
  doc.setFontSize(9);
  doc.text(new Date().toLocaleString(), W - 40, 45, { align: "right" });

  let y = 110;
  doc.setTextColor(20, 20, 30);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(`${b.manufacturer} ${b.model ?? ""}`, 40, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Battery Code: ${b.battery_code}`, 40, y);
  y += 14;
  doc.text(`Passport ID: ${b.id}`, 40, y);
  y += 24;

  // trust score block
  doc.setFillColor(245, 248, 255);
  doc.roundedRect(40, y, W - 80, 80, 6, 6, "F");
  doc.setFontSize(11);
  doc.setTextColor(80, 90, 110);
  doc.text("Battery Trust Score", 60, y + 22);
  doc.setFontSize(40);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 110, 220);
  doc.text(String(score), 60, y + 65);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 60);
  doc.text(`Rating: ${cat.label}`, 180, y + 35);
  doc.text(`State of Health: ${soh}%`, 180, y + 55);
  doc.text(`Recommendation: ${cat.recommendation}`, 360, y + 35);
  doc.text(`Lifecycle: ${b.lifecycle_status.replace(/_/g, " ")}`, 360, y + 55);
  y += 110;

  // specs table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(20, 20, 30);
  doc.text("Specifications", 40, y);
  y += 8;
  doc.setDrawColor(220);
  doc.line(40, y, W - 40, y);
  y += 14;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const rows: [string, string][] = [
    ["Chemistry", b.chemistry],
    ["Manufacturing Date", b.manufacturing_date],
    ["Original Capacity", `${b.original_capacity_kwh} kWh`],
    ["Current Capacity", `${b.current_capacity_kwh} kWh`],
    ["Charge Cycles", String(b.charge_cycles)],
    ["Avg Operating Temp", `${b.avg_operating_temp_c} °C`],
    ["Fast Charging Frequency", `${b.fast_charging_freq_pct}%`],
    ["Voltage", `${b.voltage_v} V`],
    ["Current", `${b.current_a} A`],
    ["Fault Count", String(b.fault_count)],
  ];
  rows.forEach(([k, v]) => {
    doc.setTextColor(90, 100, 120);
    doc.text(k, 50, y);
    doc.setTextColor(20, 20, 30);
    doc.text(v, 260, y);
    y += 16;
  });

  y += 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Notes & History", 40, y);
  y += 8;
  doc.line(40, y, W - 40, y);
  y += 14;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const wrap = (label: string, txt: string | null) => {
    doc.setTextColor(90, 100, 120);
    doc.text(label, 50, y);
    y += 14;
    doc.setTextColor(20, 20, 30);
    const lines = doc.splitTextToSize(txt || "—", W - 100);
    doc.text(lines, 60, y);
    y += lines.length * 12 + 10;
  };
  wrap("Fault Records", b.fault_records);
  wrap("Maintenance Notes", b.maintenance_notes);
  wrap("Inspection Notes", b.inspection_notes);
  wrap("Recommended Use", cat.use);

  doc.setFontSize(8);
  doc.setTextColor(140);
  doc.text(
    "Generated by VoltPass — Trust for the Second Life of EV Batteries",
    40,
    doc.internal.pageSize.getHeight() - 24,
  );

  doc.save(`voltpass-${b.battery_code}.pdf`);
}
